version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    versioning-strategy: lockfile-only
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "brace-expansion"
      - dependency-name: "tar"
      - dependency-name: "js-yaml"
